class Calculator
{
public static void main(String args[])
{
System.out.println("Hello World!!!);
System.out.println("Now, change the code in both the branch file");
System.out.println("And pull the requests of both the branchs");
System.out.println("Merge it with staging");
System.out.println("And then check the conflict occur or not");
System.out.println("To see Merge conflict");
System.out.println("Create two branch from Staging branch");
System.out.println("Dev1 and Dev2");
}
}